name: Winlator-lib

on:
  workflow_dispatch:

jobs:
  build:
    name: "Winlator-lib"
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        sudo apt update && sudo apt install -y libarchive-tools wget
        
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
        
    - name: Setup gradle
      uses: gradle/wrapper-validation-action@v2
      
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup cache
      uses: actions/cache@v4
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Build
      run: chmod +x ./gradlew && ./gradlew assembleDebug
    
    - name: Upload Winlator-lib
      uses: actions/upload-artifact@v4
      with:
        name: winlator-arm64-v8-debug-lib
        path: ./app/build/outputs/aar/*.aar
    

    # - name: Update Nightly Release
    #   uses: andelf/nightly-release@main
    #   if: github.repository == 'termux/termux-x11' && github.ref == 'refs/heads/master'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: nightly
    #     name: 'Nightly Release $$'
    #     draft: false
    #     prerelease: false
    #     body: |
    #       This is a nightly release of the termux-x11 app.
    #       Based on ${{ github.sha }}
    #     files: |
    #       ./app/build/outputs/apk/debug/app-*-debug.apk
    #       ./app/build/outputs/apk/debug/shell-loader-nightly.apk
    #       ./app/build/outputs/apk/debug/termux-x11-*-all.deb
    #       ./app/build/outputs/apk/debug/termux-x11-*-any.pkg.tar.xz
